name: Server CI

on:
  pull_request:
    branches: [dev]

env:
  directory-server: ./back-end

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TYPEORM_USERNAME }}
          MYSQL_DATABSE: ${{ secrets.TYPEORM_DATABASE }}
        ports: ${{ secrets.TYPEORM_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ${{env.directory-server}}
        run: npm i

      - name: Test
        working-directory: ${{env.directory-server}}
        run: npm test
        env:
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          TYPEORM_HOST: ${{ secrets.TYPEORM_HOST }}
          TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
          TYPEORM_USERNAME: ${{ secrets.TYPEORM_USERNAME }}
          TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
          TYPEORM_DATABASE: ${{ secrets.TYPEORM_DATABASE }}
          EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
