name: Server CI

on:
  pull_request:
    branches: [dev]

env:
  directory-server: ./back-end

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABSE: liargame
        ports:
          - 3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ${{env.directory-server}}
        run: npm i

      - name: Test
        working-directory: ${{env.directory-server}}
        run: npm test
        env:
          COOKIE_SECRET: test
          TYPEORM_HOST: localhost
          TYPEORM_PORT: 3306
          TYPEORM_USERNAME: root
          TYPEORM_PASSWORD: root
          TYPEORM_DATABASE: liargame
          EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
